# Generated by Django 6.0 on 2025-12-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('employee', 'EMPLOYEE'), ('manager', 'MANAGER')], default='employee', max_length=20),
        ),
    ]
