# Generated by Django 6.0 on 2025-12-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fingerprint_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
