import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Nav from "./(components2)/Nav";
// import Footer from "./(components2)/Footer";
import SubNav from "../(components2)/SubNav";
import PhotoCard from "../(components2)/PhotoCard";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      id="layout"
      className="flex flex-col  bg-gray-200 h-screen -z-30 max-h-screen"
    >
      {/* <SubNav /> */}

      <div className="flex flex-row justify-between">
        <div className="">{/* <PhotoCard /> */}</div>
        <div className="flex-grow overflow-y-auto bg-muted">{children}</div>
      </div>
    </div>
  );
}
